---

# - name: Downloading Tarball
#   get_url:
#     src: https://download.moodle.org/download.php/direct/stable38/moodle-latest-38.tgz
#     dest: /tmp/moodle.tgz

- name: Unpack moodle tarball
  unarchive:
    src: https://download.moodle.org/download.php/direct/stable38/moodle-latest-38.tgz
    dest: /var/www
    remote_src: True
    owner: www-data
    group: www-data
    mode: 0755

- name: Install Dependencies
  apt:
    name:
      - libapache2-mod-php
      - php-mysql
      - php-zip
      - php-curl
      - php-xml
      - php-gd
      - php-intl
      - php-mbstring
      - php-xmlrpc
      - php-soap
    state: present

- name: Creating Moodle Database
  mysql_db:
    name: moodle
    login_user: root
    state: present

- name: Create Moodle Database User
  mysql_user:
    name: moodle
    password: moodle
    priv: "moodle.*:ALL"
    state: present

- name: Create datapath
  file:
    path: {{ data_path }}
    state: directory
    owner: www-data
    group: www-data
    mode: 0755