---

- name: Install Moodle Dependencies
  apt:
    name:
      - git
      - libapache2-mod-php
      - php-mysql
      - php-zip
      - php-curl
      - php-xml
      - php-gd
      - php-intl
      - php-mbstring
      - php-xmlrpc
      - php-soap
    state: present

- name: Cloning moodle codebase
  git:
    repo: git://git.moodle.org/moodle.git
    dest: "{{ moodle_webroot }}"
    version: "MOODLE_{{ moodle_version }}_STABLE"

- name: Creating Moodle Database
  mysql_db:
    name: "{{ moodle_mysql_database }}"
    login_user: "{{ moodle_mysql_login_user }}"
    login_password: "{{ moodle_mysql_login_password | default('') }}"
    login_host: "{{ moodle_mysql_host }}"
    state: present

- name: Create Moodle Database User
  mysql_user:
    name: "{{ moodle_mysql_username }}"
    password: "{{ moodle_mysql_password }}"
    priv: "{{ moodle_mysql_database }}.*:ALL"
    login_user: "{{ moodle_mysql_login_user }}"
    login_password: "{{ moodle_mysql_login_password | default('') }}"
    login_host: "{{ moodle_mysql_host }}"
    state: present

- name: Create datapath
  file:
    path: "{{ moodle_data_path }}"
    state: directory
    owner: www-data
    group: www-data
    mode: 0777

- name: check for installed apache2
  stat:
    path: /usr/sbin/apache2
  register: apache2

- name: enroll apache2 vhost for moodle
  template:
    src: apache-vhost.conf.j2
    dest: "/etc/apache2/sites-enabled/{{ moodle_domain }}.conf"
    owner: root
    group: root
    mode: 0644
  when: apache2.stat.exists
  notify: restart apache

- name: enroll moodle config
  template:
    src: moodle-config.php.j2
    dest: "{{ moodle_webroot }}/config.php"
