---

- name: Cloning moodle codebase
  ansible.builtin.git:
    repo: git://git.moodle.org/moodle.git
    dest: "{{ moodle_webroot }}"
    version: "MOODLE_{{ moodle_version }}_STABLE"
  become: True
  notify: Run moodle upgrades

- name: Creating Moodle Database
  community.mysql.mysql_db:
    name: "{{ moodle_mysql_database }}"
    login_user: "{{ moodle_mysql_login_user }}"
    login_password: "{{ moodle_mysql_login_password | default('') }}"
    login_host: "{{ moodle_mysql_host }}"
    state: present

- name: Create Moodle Database User
  community.mysql.mysql_user:
    name: "{{ moodle_mysql_username }}"
    password: "{{ moodle_mysql_password }}"
    priv: "{{ moodle_mysql_database }}.*:ALL"
    login_user: "{{ moodle_mysql_login_user }}"
    login_password: "{{ moodle_mysql_login_password | default('') }}"
    login_host: "{{ moodle_mysql_host }}"
    state: present

- name: Create datapath
  ansible.builtin.file:
    path: "{{ moodle_data_path }}"
    state: directory
    owner: www-data
    group: www-data
    mode: 0777

- name: Enroll moodle config
  ansible.builtin.template:
    src: moodle-config.php.j2
    dest: "{{ moodle_webroot }}/config.php"
    owner: www-data
    group: www-data
    mode: 0755
